[package]
name = "kdb-reader"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45" }
chrono = { version = "0.4.42" }
tokio = { version = "1.24", features=[ "full" ] }
kdbplus = { version = "0.3.9", features = [ "ipc" ] }